name: Deployment
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.TOKEN }}
        

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.x

      - name: Install Packages
        run: yarn
      - name: Build page
        run: yarn build
        
      - name: commit
        run: |
          git config --global user.email "tivonfeng@163.com"
          git config --global user.name "tivonfeng"
          git add .
          git commit -m "auto deploy"
          git push origin master
